/**
 * Static Egypt governorate → markaz/district dataset for address selects.
 * Keys (value) are English; UI labels are Arabic.
 *
 * Source: Open Admin Data (CC-BY-4.0)
 * https://github.com/open-admin-data/egypt-administrative-divisions
 *
 * Decision (task 5.3): full Egypt list — not delivery-area-only.
 * Shipping fee by area remains out of MVP (backlog).
 */

export type LocationOption = {
  value: string;
  label: string;
};

export const GOVERNORATES = [
  "Aswan",
  "Assiut",
  "Alexandria",
  "Ismailia",
  "Luxor",
  "Red Sea",
  "Beheira",
  "Giza",
  "Dakahlia",
  "Suez",
  "Sharkia",
  "Gharbia",
  "Fayoum",
  "Cairo",
  "Qalyubia",
  "Menoufia",
  "Minya",
  "New Valley",
  "Beni Suef",
  "Port Said",
  "South Sinai",
  "Damietta",
  "Sohag",
  "North Sinai",
  "Qena",
  "Kafr El-Sheikh",
  "Matrouh",
] as const;

export type Governorate = (typeof GOVERNORATES)[number];

export const GOVERNORATE_LABELS: Record<Governorate, string> = {
  "Aswan": "أسوان",
  "Assiut": "أسيوط",
  "Alexandria": "الإسكندرية",
  "Ismailia": "الإسماعيلية",
  "Luxor": "الأقصر",
  "Red Sea": "البحر الأحمر",
  "Beheira": "البحيرة",
  "Giza": "الجيزة",
  "Dakahlia": "الدقهلية",
  "Suez": "السويس",
  "Sharkia": "الشرقية",
  "Gharbia": "الغربية",
  "Fayoum": "الفيوم",
  "Cairo": "القاهرة",
  "Qalyubia": "القليوبية",
  "Menoufia": "المنوفية",
  "Minya": "المنيا",
  "New Valley": "الوادي الجديد",
  "Beni Suef": "بني سويف",
  "Port Said": "بورسعيد",
  "South Sinai": "جنوب سيناء",
  "Damietta": "دمياط",
  "Sohag": "سوهاج",
  "North Sinai": "شمال سيناء",
  "Qena": "قنا",
  "Kafr El-Sheikh": "كفر الشيخ",
  "Matrouh": "مطروح",
};

export const MARKAZ_BY_GOVERNORATE: Record<Governorate, readonly string[]> = {
  "Aswan": [
    "Abu Simbel",
    "Adfu",
    "Aswan",
    "Aswan 2",
    "Daraw",
    "Kum Umbu",
    "Aswan City",
    "Tushaka",
    "Nasr",
  ],
  "Assiut": [
    "Abnub",
    "Abu Tig",
    "Assuit",
    "Al- Badari",
    "Al-Ghanayem",
    "Alfath",
    "Al-Qusia",
    "Kesm Awal Assuit",
    "Kesm Than Assuit",
    "Dayrut",
    "Sahil Silim",
    "Sidfa",
    "Assuit City",
    "Manfalut",
  ],
  "Alexandria": [
    "Al Gumruk",
    "Al Dikhila",
    "North Coast",
    "Al Amreia",
    "Al Attarin",
    "A L Labban",
    "Muntazah",
    "Al Manshiyya",
    "Al Raml",
    "Bab Sharqi",
    "Burg al-Arab",
    "Kesm than Al Raml",
    "Sidi Gabir",
    "Karmuz",
    "Muharam Bik",
    "Burg Al-Arab City",
    "Mina Al-Basal",
  ],
  "Ismailia": [
    "Ismailiyya",
    "Tal al-Kabir, al-",
    "Qantara Gharb, al-",
    "Qantara Sharq, al-",
    "Ismailiyya 1",
    "Ismailiyya 3",
    "Ismailiyya 2",
    "Fayid",
  ],
  "Luxor": [
    "Luxor",
    "Luxor 2",
    "Tiba",
  ],
  "Red Sea": [
    "Qusir",
    "Hurghada 1",
    "Hurghada 2",
    "Halayib",
    "Ras Gharib",
    "Safaga",
    "Shallatin",
    "Marsa Alam",
  ],
  "Beheira": [
    "Abu-l-Matamir",
    "Abu Hummus",
    "Idku",
    "Al-Dilingat",
    "Al-Rahmaniyya",
    "Al-Mahmudiyya",
    "Itay Al-Barud",
    "Badr",
    "Hush Isa",
    "Damanhur",
    "Damanhur 2",
    "Rashid",
    "Shubra Khit",
    "Nubariyya West",
    "Kafr Al-Dawwar 2",
    "Kafr Al-Dawwar",
    "Kum Hamada",
    "Wadi Al-NatrUn",
  ],
  "Giza": [
    "Atfeh",
    "Al-Ahram",
    "Badrashain",
    "Giza",
    "Giza 2",
    "Hwamdeia",
    "DuqqI",
    "Shaykh Zayed",
    "Saf",
    "Al-Aguza",
    "Umraniyya",
    "Ayat",
    "Bahariya Oasis",
    "Waraq",
    "Imbaba 2",
    "Imbaba",
    "Auseem",
    "6 October-1",
    "Bulaq Al-DakrUr",
    "6 October-2",
    "Kardasa",
  ],
  "Dakahlia": [
    "Aga",
    "Gamaliyya",
    "Sinbillawin",
    "Matariyya",
    "Manzala",
    "El Mansora",
    "El Mansora 1",
    "Bilqas",
    "Bany Abeed",
    "Tamy Al-Amdid",
    "E Mansora 2",
    "Gamsa",
    "Dikirnis",
    "Shirbin",
    "Talkha",
    "Mahalet Demna",
    "Minya Al-Nasr",
    "MIt Salsil",
    "Mit Ghamr",
    "Mit Ghamr 2",
    "Nebro",
  ],
  "Suez": [
    "Al-Arbiin",
    "Al-Ganayin",
    "Suez",
    "Ataqa",
    "Faysal",
  ],
  "Sharkia": [
    "Abu Hammad",
    "Abu Kabir",
    "El-Ibrahimiya",
    "Al-Husayniya",
    "Zaqaziq",
    "Al-Salhiyya",
    "Qurin",
    "Al-Qanayat",
    "Zaqaziq 1",
    "10 Ramadan 1",
    "Awlad Saqr",
    "Bilbis",
    "Zaqaziq 2",
    "10 Ramadan 2",
    "Dyarb Nigm",
    "Faqus",
    "Faqus 2",
    "Kafr Saqr",
    "Mashtul Al-Suq",
    "Minya al-Qamh",
    "Hihya",
  ],
  "Gharbia": [
    "Santa",
    "El Mahalla El Kobra",
    "El Mahalla El Kobra 1",
    "Tanta 1",
    "Basyun",
    "El Mahalla El Kobra 2",
    "Tanta 2",
    "Zifta",
    "Samannud",
    "Tanta",
    "Qutur",
    "Kafr Al-Zayyat",
  ],
  "Fayoum": [
    "Abshaway",
    "Atsa",
    "Fayyum",
    "Fayyum 2",
    "Sinuras",
    "Tamya",
    "Fayyum City",
    "Yousef El sadeq",
  ],
  "Cairo": [
    "15 Mayu",
    "Al Azbakiyya",
    "Basatin",
    "Al Tibbin",
    "Gamaliyya",
    "Al Khalifa",
    "Al Darb al-Ahmar",
    "Zawiyya Al-Hamra",
    "Zamalik",
    "Al Zaytun",
    "Al Sahil",
    "Al Salam",
    "Sayyida Zainab",
    "Al Sharabiyya",
    "Shroq",
    "Al Zahir",
    "Marg",
    "Al Matariyya",
    "Maadi",
    "Muski",
    "Nuzha",
    "Al Wayli",
    "New Cairo-1",
    "Nasr City",
    "Bab Al-Shariyya",
    "Badr",
    "Bulaq",
    "New Cairo-3",
    "New Cairo-2",
    "Madinat Nasr-2",
    "Hadaiq Al-Qubba",
    "Hilwan",
    "Rud Al-Farag",
    "Shubra",
    "Tura",
    "Abdin",
    "Ain Shams",
    "Qasr Al-Nile",
    "Misr al-Gadida",
    "Misr Al-Qadima",
    "Minshat Nasir",
  ],
  "Qalyubia": [
    "Al Khanka",
    "Khsos",
    "Abour",
    "Qanatir Al-Khayriyya",
    "Shubra Al-Khayma 1",
    "Banha",
    "Banha 2",
    "Shubra Al-Khayma 2",
    "Shibin al-Qanatir",
    "Tukh",
    "Qalyub",
    "Qalyub 2",
    "Qaha",
    "Kafr Shukr",
  ],
  "Menoufia": [
    "Ashmun",
    "Al-Bagur",
    "Sadat City",
    "Al-Shuhada",
    "Birkat Al-Sab",
    "Tala",
    "Shibin al-Kum",
    "Shibin al-Kum 2",
    "Quwisna",
    "Sirs Al-Layyana City",
    "Minuf City",
    "Minuf",
  ],
  "Minya": [
    "Markz Abu Qurqas",
    "Markz Al Idwa",
    "Kesm Al-minya",
    "Markz Al Minya",
    "Markz Bani Mazar",
    "Markz Dir Mawas",
    "Markz Samalut",
    "New Minya",
    "Markz Matay",
    "Markz Maghagha",
    "Kesm Mallawi",
    "Markz Mallawi",
  ],
  "New Valley": [
    "Al Farafra Oasis",
    "Al-Kharga Oasis",
    "A-Dakhla Oasis",
    "Paris Paris",
  ],
  "Beni Suef": [
    "Al Fashn",
    "Al Wasta",
    "Ahnasya",
    "Biba",
    "Bani Swayf",
    "Bani Swayf 2",
    "Sumusta",
    "Bani Swayf City",
    "Nasir",
  ],
  "Port Said": [
    "Al-Ganoub",
    "Al-Zohour",
    "Al-Sharq",
    "Al-Dawahy",
    "Al-Arab",
    "Al-Munakh",
    "Al-Manasra",
    "Port Fuad",
    "Al-Ganoub 2",
    "Port Fuad 2",
    "Mubark-Sharq Tafrea",
  ],
  "South Sinai": [
    "Abu Radis",
    "Al-Tur",
    "Dahab",
    "Ras Sidr",
    "Sant Katrin",
    "Sharm el-Sheikh",
    "Taba",
    "Nuweiba",
  ],
  "Damietta": [
    "Zarqa",
    "Dumyat 1",
    "Dumyat 2",
    "Dumyat",
    "Ras al-Bar",
    "Fariskur",
    "Kafr Sad",
    "Dumyat Al-Gadida",
  ],
  "Sohag": [
    "Akhmim",
    "Al-Balyana",
    "Al Usayrat",
    "Kawther",
    "Al-Maragha",
    "Al-Minshat",
    "Sohag",
    "Suhag-2",
    "Girga",
    "Girga 2",
    "Guhayna Al-Gharbiyya",
    "Dar al-Salam",
    "Saqulta",
    "Sohag 2",
    "Tama",
    "Kesm Tahta",
    "Tahta",
    "Akhmim City",
    "Suhag City",
  ],
  "North Sinai": [
    "Al-Hasna",
    "Shaykh Zuwayd",
    "Qasima",
    "El Arish 1",
    "Bir Al-Abd",
    "El Arish 3",
    "El Arish 2",
    "El Arish 4",
    "Rafah",
    "Rummana",
    "Nakhl",
  ],
  "Qena": [
    "Abu Tisht",
    "Armant",
    "Isna",
    "Al Waqf",
    "Dishna",
    "Farshut",
    "Qift",
    "Qina",
    "Qina 2",
    "Qus",
    "Qina City",
    "Nag Hammadi",
    "Naqada",
  ],
  "Kafr El-Sheikh": [
    "Burullus",
    "Al Hamul",
    "Riyad",
    "Biyalu",
    "Disuq",
    "Disuq 2",
    "Sidi Salim",
    "Fuwwa",
    "Qillin",
    "Kafr Al-Shaykh",
    "Kafr Al-Shaykh 2",
    "Mitubas",
  ],
  "Matrouh": [
    "Al-Hammam",
    "North Coast",
    "Salloum",
    "Daba",
    "Sidi Barani",
    "Siwa",
    "Alamn",
    "Marsa Matruh",
  ],
};

export const MARKAZ_LABELS: {
  readonly [G in Governorate]: Readonly<
    Record<(typeof MARKAZ_BY_GOVERNORATE)[G][number], string>
  >;
} = {
  "Aswan": {
    "Abu Simbel": "أبوسنبل",
    "Adfu": "أدفو",
    "Aswan": "أسوان (قسم)",
    "Aswan 2": "أسوان (مركز)",
    "Daraw": "دراو",
    "Kum Umbu": "كوم امبو",
    "Aswan City": "مدينة أسوان الجديدة",
    "Tushaka": "مدينة توشكى الجديدة",
    "Nasr": "نصر",
  },
  "Assiut": {
    "Abnub": "أبنوب",
    "Abu Tig": "أبوتيج",
    "Assuit": "أسيوط",
    "Al- Badari": "البدارى",
    "Al-Ghanayem": "الغنايم",
    "Alfath": "الفتح",
    "Al-Qusia": "القوصية",
    "Kesm Awal Assuit": "أول أسيوط",
    "Kesm Than Assuit": "ثان أسيوط",
    "Dayrut": "ديروط",
    "Sahil Silim": "ساحل سليم",
    "Sidfa": "صدفا",
    "Assuit City": "مدينة اسيوط الجديدة",
    "Manfalut": "منفلوط",
  },
  "Alexandria": {
    "Al Gumruk": "الجمرك",
    "Al Dikhila": "الدخيلة",
    "North Coast": "الساحل الشمالى",
    "Al Amreia": "العامرية",
    "Al Attarin": "العطارين",
    "A L Labban": "اللبان",
    "Muntazah": "المنتزة",
    "Al Manshiyya": "المنشية",
    "Al Raml": "أول الرمل",
    "Bab Sharqi": "باب شرقى",
    "Burg al-Arab": "برج العرب",
    "Kesm than Al Raml": "ثان الرمل",
    "Sidi Gabir": "سيدى جابر",
    "Karmuz": "كرموز",
    "Muharam Bik": "محرم بك",
    "Burg Al-Arab City": "مدينه برج العرب الجديده",
    "Mina Al-Basal": "مينا البصل",
  },
  "Ismailia": {
    "Ismailiyya": "الاسماعيلية",
    "Tal al-Kabir, al-": "التل الكبير",
    "Qantara Gharb, al-": "القنطرة",
    "Qantara Sharq, al-": "القنطرة شرق",
    "Ismailiyya 1": "أول الاسماعيلية",
    "Ismailiyya 3": "ثالث الاسماعيلية",
    "Ismailiyya 2": "ثان الاسماعيلية",
    "Fayid": "فايد",
  },
  "Luxor": {
    "Luxor": "الأقصر (قسم)",
    "Luxor 2": "الأقصر (مركز)",
    "Tiba": "طيبة",
  },
  "Red Sea": {
    "Qusir": "القصير",
    "Hurghada 1": "أول الغردقة",
    "Hurghada 2": "ثان الغردقة",
    "Halayib": "حلايب",
    "Ras Gharib": "رأس غارب",
    "Safaga": "سفاجا",
    "Shallatin": "شلاتين",
    "Marsa Alam": "مرسى علم",
  },
  "Beheira": {
    "Abu-l-Matamir": "ابوالمطامير",
    "Abu Hummus": "ابوحمص",
    "Idku": "إدكو",
    "Al-Dilingat": "الدلنجات",
    "Al-Rahmaniyya": "الرحمانية",
    "Al-Mahmudiyya": "المحمودية",
    "Itay Al-Barud": "إيتاى البارود",
    "Badr": "بدر",
    "Hush Isa": "حوش عيسى",
    "Damanhur": "دمنهور (قسم)",
    "Damanhur 2": "دمنهور (مركز)",
    "Rashid": "رشيد",
    "Shubra Khit": "شبراخيت",
    "Nubariyya West": "غرب النوبارية",
    "Kafr Al-Dawwar 2": "كفر الدوار",
    "Kafr Al-Dawwar": "كفرالدوار",
    "Kum Hamada": "كوم حمادة",
    "Wadi Al-NatrUn": "وادى النطرون",
  },
  "Giza": {
    "Atfeh": "أطفيح",
    "Al-Ahram": "الأهرام",
    "Badrashain": "البدرشين",
    "Giza": "الجيزة (قسم)",
    "Giza 2": "الجيزة (مركز)",
    "Hwamdeia": "الحوامدية",
    "DuqqI": "الدقي",
    "Shaykh Zayed": "الشيخ زايد",
    "Saf": "الصف",
    "Al-Aguza": "العجوزة",
    "Umraniyya": "العمرانية",
    "Ayat": "العياط",
    "Bahariya Oasis": "الواحاتالبحرية",
    "Waraq": "الوراق",
    "Imbaba 2": "إمبابة",
    "Imbaba": "امبابه",
    "Auseem": "أوسيم",
    "6 October-1": "أول 6 أكتوبر",
    "Bulaq Al-DakrUr": "بولاق الدكرور",
    "6 October-2": "ثان 6 أكتوبر",
    "Kardasa": "كرداسة",
  },
  "Dakahlia": {
    "Aga": "أجا",
    "Gamaliyya": "الجمالية",
    "Sinbillawin": "السنبلاوين",
    "Matariyya": "المطرية",
    "Manzala": "المنزلة",
    "El Mansora": "المنصورة",
    "El Mansora 1": "اول المنصورة",
    "Bilqas": "بلقاس",
    "Bany Abeed": "بنى عبيد",
    "Tamy Al-Amdid": "تمى الأمديد",
    "E Mansora 2": "ثان المنصورة",
    "Gamsa": "جمصة",
    "Dikirnis": "دكرنس",
    "Shirbin": "شربين",
    "Talkha": "طلخا",
    "Mahalet Demna": "محلة دمنة",
    "Minya Al-Nasr": "منية النصر",
    "MIt Salsil": "ميت سلسيل",
    "Mit Ghamr": "ميت غمر (قسم)",
    "Mit Ghamr 2": "ميت غمر (مركز)",
    "Nebro": "نبروة",
  },
  "Suez": {
    "Al-Arbiin": "الأربعين",
    "Al-Ganayin": "الجناين",
    "Suez": "السويس",
    "Ataqa": "عتاقة",
    "Faysal": "فيصل",
  },
  "Sharkia": {
    "Abu Hammad": "أبو حماد",
    "Abu Kabir": "أبوكبير",
    "El-Ibrahimiya": "الأبراهيمية",
    "Al-Husayniya": "الحسينية",
    "Zaqaziq": "الزقازيق",
    "Al-Salhiyya": "الصالحية الجديدة",
    "Qurin": "القرين",
    "Al-Qanayat": "القنايات",
    "Zaqaziq 1": "اول الزقازيق",
    "10 Ramadan 1": "اول مدينة العاشر من رمضان",
    "Awlad Saqr": "أولاد صقر",
    "Bilbis": "بلبيس",
    "Zaqaziq 2": "ثان الزقازيق",
    "10 Ramadan 2": "ثان مدينه العاشر من رمضان",
    "Dyarb Nigm": "ديرب نجم",
    "Faqus": "فاقوس (قسم)",
    "Faqus 2": "فاقوس (مركز)",
    "Kafr Saqr": "كفر صقر",
    "Mashtul Al-Suq": "مشتول السوق",
    "Minya al-Qamh": "منيا القمح",
    "Hihya": "ههيا",
  },
  "Gharbia": {
    "Santa": "السنطة",
    "El Mahalla El Kobra": "المحله الكبرى",
    "El Mahalla El Kobra 1": "أول المحلة الكبرى",
    "Tanta 1": "أول طنطا",
    "Basyun": "بسيون",
    "El Mahalla El Kobra 2": "ثان المحلة الكبرى",
    "Tanta 2": "ثان طنطا",
    "Zifta": "زفتى",
    "Samannud": "سمنود",
    "Tanta": "طنطا",
    "Qutur": "قطور",
    "Kafr Al-Zayyat": "كفر الزيات",
  },
  "Fayoum": {
    "Abshaway": "أبشواى",
    "Atsa": "أطسا",
    "Fayyum": "الفيوم (قسم)",
    "Fayyum 2": "الفيوم (مركز)",
    "Sinuras": "سنورس",
    "Tamya": "طامية",
    "Fayyum City": "مدينة الفيوم الجديدة",
    "Yousef El sadeq": "يوسف الصديق",
  },
  "Cairo": {
    "15 Mayu": "15 مايو",
    "Al Azbakiyya": "الأزبكية",
    "Basatin": "البساتين",
    "Al Tibbin": "التبين",
    "Gamaliyya": "الجمالية",
    "Al Khalifa": "الخليفة",
    "Al Darb al-Ahmar": "الدرب الأحمر",
    "Zawiyya Al-Hamra": "الزاويةالحمراء",
    "Zamalik": "الزمالك",
    "Al Zaytun": "الزيتون",
    "Al Sahil": "الساحل",
    "Al Salam": "السلام",
    "Sayyida Zainab": "السيدة زينب",
    "Al Sharabiyya": "الشرابية",
    "Shroq": "الشروق",
    "Al Zahir": "الظاهر",
    "Marg": "المرج",
    "Al Matariyya": "المطرية",
    "Maadi": "المعادي",
    "Muski": "الموسكي",
    "Nuzha": "النزهة",
    "Al Wayli": "الوايلي",
    "New Cairo-1": "أول القاهرة الجديدة",
    "Nasr City": "أول مدينة نصر",
    "Bab Al-Shariyya": "باب الشعرية",
    "Badr": "بدر",
    "Bulaq": "بولاق",
    "New Cairo-3": "ثالث القاهرة الجديدة",
    "New Cairo-2": "ثان القاهرة الجديدة",
    "Madinat Nasr-2": "ثانمدينةنصر",
    "Hadaiq Al-Qubba": "حدائقالقبة",
    "Hilwan": "حلوان",
    "Rud Al-Farag": "روضالفرج",
    "Shubra": "شبرا",
    "Tura": "طره",
    "Abdin": "عابدين",
    "Ain Shams": "عينشمس",
    "Qasr Al-Nile": "قصر النيل",
    "Misr al-Gadida": "مصرالجديدة",
    "Misr Al-Qadima": "مصرالقديمة",
    "Minshat Nasir": "منشأةناصر",
  },
  "Qalyubia": {
    "Al Khanka": "الخانكة",
    "Khsos": "الخصوص",
    "Abour": "العبور",
    "Qanatir Al-Khayriyya": "القناطر الخيرية",
    "Shubra Al-Khayma 1": "أول شبرا الخيمة",
    "Banha": "بنها (قسم)",
    "Banha 2": "بنها (مركز)",
    "Shubra Al-Khayma 2": "ثان شبرا الخيمة",
    "Shibin al-Qanatir": "شبين القناطر",
    "Tukh": "طوخ",
    "Qalyub": "قليوب (قسم)",
    "Qalyub 2": "قليوب (مركز)",
    "Qaha": "قها",
    "Kafr Shukr": "كفر شكر",
  },
  "Menoufia": {
    "Ashmun": "أشمون",
    "Al-Bagur": "الباجور",
    "Sadat City": "السادات",
    "Al-Shuhada": "الشهداء",
    "Birkat Al-Sab": "بركة السبع",
    "Tala": "تلا",
    "Shibin al-Kum": "شبين الكوم (قسم)",
    "Shibin al-Kum 2": "شبين الكوم (مركز)",
    "Quwisna": "قويسنا",
    "Sirs Al-Layyana City": "مدينة سرس الليانة",
    "Minuf City": "مدينة منوف",
    "Minuf": "منوف",
  },
  "Minya": {
    "Markz Abu Qurqas": "ابو قرقاص",
    "Markz Al Idwa": "العدوة",
    "Kesm Al-minya": "المنيا (قسم)",
    "Markz Al Minya": "المنيا (مركز)",
    "Markz Bani Mazar": "بنى مزار",
    "Markz Dir Mawas": "دير مواس",
    "Markz Samalut": "سمالوط",
    "New Minya": "مدينة المنيا الجديدة",
    "Markz Matay": "مطاى",
    "Markz Maghagha": "مغاغة",
    "Kesm Mallawi": "ملوى (قسم)",
    "Markz Mallawi": "ملوى (مركز)",
  },
  "New Valley": {
    "Al Farafra Oasis": "الفرافرة",
    "Al-Kharga Oasis": "الواحات الخارجة",
    "A-Dakhla Oasis": "الوحات الداخلة",
    "Paris Paris": "باريس",
  },
  "Beni Suef": {
    "Al Fashn": "الفشن",
    "Al Wasta": "الواسطى",
    "Ahnasya": "أهناسيا",
    "Biba": "ببا",
    "Bani Swayf": "بنى سويف (قسم)",
    "Bani Swayf 2": "بنى سويف (مركز)",
    "Sumusta": "سمسطا",
    "Bani Swayf City": "مدينة بنى سويف الجديدة",
    "Nasir": "ناصر",
  },
  "Port Said": {
    "Al-Ganoub": "الجنوب",
    "Al-Zohour": "الزهور",
    "Al-Sharq": "الشرق",
    "Al-Dawahy": "الضواحى",
    "Al-Arab": "العرب",
    "Al-Munakh": "المناخ",
    "Al-Manasra": "المناصرة",
    "Port Fuad": "بور فؤاد",
    "Al-Ganoub 2": "ثان الجنوب",
    "Port Fuad 2": "ثان بور فؤاد",
    "Mubark-Sharq Tafrea": "مبارك - شرق التفريعة",
  },
  "South Sinai": {
    "Abu Radis": "أبو رديس",
    "Al-Tur": "الطور",
    "Dahab": "دهب",
    "Ras Sidr": "رأس سدر",
    "Sant Katrin": "سانت كاترين",
    "Sharm el-Sheikh": "شرم الشيخ",
    "Taba": "طابا",
    "Nuweiba": "نويبع",
  },
  "Damietta": {
    "Zarqa": "الزرقا",
    "Dumyat 1": "أول دمياط",
    "Dumyat 2": "ثان دمياط",
    "Dumyat": "دمياط",
    "Ras al-Bar": "رأس البر",
    "Fariskur": "فارسكور",
    "Kafr Sad": "كفر سعد",
    "Dumyat Al-Gadida": "مدينه دمياط الجديده",
  },
  "Sohag": {
    "Akhmim": "أخميم",
    "Al-Balyana": "البلينا",
    "Al Usayrat": "العسيرات",
    "Kawther": "الكوثر",
    "Al-Maragha": "المراغة",
    "Al-Minshat": "المنشأة",
    "Sohag": "اول سوهاج",
    "Suhag-2": "ثان سوهاج",
    "Girga": "جرجا (قسم)",
    "Girga 2": "جرجا (مركز)",
    "Guhayna Al-Gharbiyya": "جهينة الغربية",
    "Dar al-Salam": "دار السلام",
    "Saqulta": "ساقلته",
    "Sohag 2": "سوهاج",
    "Tama": "طما",
    "Kesm Tahta": "طهطا (قسم)",
    "Tahta": "طهطا (مركز)",
    "Akhmim City": "مدينة أخميم الجديدة",
    "Suhag City": "مدينة سوهاج الجديدة",
  },
  "North Sinai": {
    "Al-Hasna": "الحسنة",
    "Shaykh Zuwayd": "الشيخ زويد",
    "Qasima": "القسيمة",
    "El Arish 1": "أول العريش",
    "Bir Al-Abd": "بئر العبد",
    "El Arish 3": "ثالث العريش",
    "El Arish 2": "ثان العريش",
    "El Arish 4": "رابع العريش",
    "Rafah": "رفح",
    "Rummana": "رمانة",
    "Nakhl": "نخل",
  },
  "Qena": {
    "Abu Tisht": "أبو طشت",
    "Armant": "أرمنت",
    "Isna": "إسنا",
    "Al Waqf": "الوقف",
    "Dishna": "دشنا",
    "Farshut": "فرشوط",
    "Qift": "قفط",
    "Qina": "قنا (قسم)",
    "Qina 2": "قنا (مركز)",
    "Qus": "قوص",
    "Qina City": "مدينة قنا الجديدة",
    "Nag Hammadi": "نجع حمادى",
    "Naqada": "نقادة",
  },
  "Kafr El-Sheikh": {
    "Burullus": "البرلس",
    "Al Hamul": "الحامول",
    "Riyad": "الرياض",
    "Biyalu": "بيلا",
    "Disuq": "دسوق (قسم)",
    "Disuq 2": "دسوق (مركز)",
    "Sidi Salim": "سيدى سالم",
    "Fuwwa": "فوه",
    "Qillin": "قلين",
    "Kafr Al-Shaykh": "كفر الشيخ (قسم)",
    "Kafr Al-Shaykh 2": "كفر الشيخ (مركز)",
    "Mitubas": "مطوبس",
  },
  "Matrouh": {
    "Al-Hammam": "الحمام",
    "North Coast": "الساحل الشمالى-جزء",
    "Salloum": "السلوم",
    "Daba": "الضبعة",
    "Sidi Barani": "سيدى برانى",
    "Siwa": "سيوة",
    "Alamn": "مارينا العلمين السياحية",
    "Marsa Matruh": "مرسى مطروح",
  },
};

export function getGovernorates(): LocationOption[] {
  return GOVERNORATES.map((value) => ({
    value,
    label: GOVERNORATE_LABELS[value],
  }));
}

export function getMarkazByGovernorate(
  governorate: string,
): LocationOption[] {
  if (!isGovernorate(governorate)) return [];
  const markazList = MARKAZ_BY_GOVERNORATE[governorate];
  const labels = MARKAZ_LABELS[governorate];
  return markazList.map((value) => ({
    value,
    label: labels[value as keyof typeof labels],
  }));
}

export function isGovernorate(value: string): value is Governorate {
  return (GOVERNORATES as readonly string[]).includes(value);
}

export function isMarkazForGovernorate(
  governorate: string,
  markaz: string,
): boolean {
  if (!isGovernorate(governorate)) return false;
  return (MARKAZ_BY_GOVERNORATE[governorate] as readonly string[]).includes(
    markaz,
  );
}

/** Arabic label for a governorate value, or the raw value if unknown. */
export function resolveGovernorateLabel(
  governorate: string | null | undefined,
): string | null {
  if (!governorate) return null;
  if (isGovernorate(governorate)) return GOVERNORATE_LABELS[governorate];
  return governorate;
}

/** Arabic label for a markaz value under a governorate, or the raw value. */
export function resolveMarkazLabel(
  governorate: string | null | undefined,
  markaz: string | null | undefined,
): string | null {
  if (!markaz) return null;
  if (!governorate) return markaz;
  const match = getMarkazByGovernorate(governorate).find(
    (option) => option.value === markaz,
  );
  return match?.label ?? markaz;
}
